
spring:
  redis:
    host: localhost
    port: 6379

  application:
    name: myfirstproject

  data:
    mongodb:
      uri: mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@cluster0.b1chi54.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /api
