spring.application.name=myfirstproject

spring.data.mongodb.uri=mongodb+srv://pradeeppal1434_db_user:Pradeeppal9676@cluster0.b1chi54.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.auto-index-creation=true