spring.application.name=myfirstproject

spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG
spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

spring.kafka.properties.ssl.truststore.location=classpath:kafka/aiven-kafka-truststore.jks
spring.kafka.properties.ssl.truststore.password=${KAFKA_TRUSTSTORE_PASSWORD}
spring.kafka.properties.ssl.truststore.type=JKS