
spring:
  application:
    name: myfirstproject

  data:
    redis:
      host:  demure-cushy-micropure-76019.db.redis.io
      port: 10420
      username: default
      password:
      ssl:
        enabled: false


    mongodb:
      uri: mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@cluster0.b1chi54.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /api
